version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Test
          command: npm run test
  publish:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Publish
          command: npm run publish
workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - publish:
          requires:
            - test
